version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  db:
    image: postgres:14
    container_name: postgres_mqtt
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ceres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_mqtt:/var/lib/postgresql/data

volumes:
  postgres_data_mqtt:
